name: '[Support] Review based card movements'
on:
  pull_request:
    types:
      - review_requested
      - synchronize
permissions:
  repository-projects: write
  contents: read
  issues: read
  pull-requests: read
concurrency:
  group: card-movement-${{ github.event.number }}
jobs:
  handler:
    runs-on: ubuntu-latest
    # This job will ignore:
    # * Events triggered by bitnami-bot (README commits for example).
    # * Events triggered over automated PRs (They are managed in comments.yml workflow).
    # * PRs with 'bitnami' label.
    if: |
      github.actor != 'bitnami-bot' && github.event.pull_request.user.login != 'bitnami-bot' &&
      (!contains(github.event.pull_request.labels.*.name, 'bitnami')) && (!contains(github.event.pull_request.labels.*.name, 'triage'))
    steps:
      - name: Repo checkout
        uses: actions/checkout@v3
        with:
          # Checkout from base to try to get latest information from the main branch.
          ref: ${{ github.event.pull_request.base.ref }}
          repository: ${{ github.event.pull_request.base.repo.full_name }}
      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          path: .github/workflows/
      - name: Move into In Progress
        # Move the card only if the actor is not a Bitnami member
        if: ${{ !contains(fromJson(env.BITNAMI_TEAM), github.actor) }}
        uses: peter-evans/create-or-update-project-card@v2
        with:
          project-name: Support
          column-name: In progress
          issue-number: ${{ github.event.number }}
