name: Sync bitnami/charts index.yaml to S3

on:
  push:
    branches:
    - index

jobs:
  deploy:
    name: Sync bitnami/charts index.yaml to S3
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install s3cmd
      run: sudo apt-get install -y s3cmd
    - name: Upload to S3
      run: |
        s3cmd put --region=${{ secrets.AWS_REGION }} --access_key=${{ secrets.AWS_ACCESS_KEY_ID }} --secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }} --acl public-read --follow-symlinks --delete bitnami/index.yaml s3://${{ secrets.AWS_S3_BUCKET }}/bitnami/
