name: 'vib'
on: # rebuild any PRs and main branch changes
  pull_request_target:
    branches:
      - master
    paths:
      - 'bitnami/airflow/*'
env:
  CSP_API_URL: https://console.cloud.vmware.com
  CSP_API_TOKEN: ${{ secrets.CSP_API_TOKEN }}
  VIB_PUBLIC_URL: https://cp.bromelia.vmware.com
jobs:
  vib-verify: 
    runs-on: ubuntu-latest
    environment: vmware-image-builder
    strategy:
      matrix:
       include:
         - target-platform: Tanzu Kubernetes Grid
           target-platform-id: 7ddab896-2e4e-4d58-a501-f79897eba3a0
      fail-fast: false
    name: Airflow on ${{ matrix.target-platform }}
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          repository: ${{ github.event.pull_request.head.repo.full_name }}
      - uses: vmware-labs/vmware-image-builder-action@main
        with:
          pipeline: airflow/vib-complete-verify.json
        env:
          VIB_ENV_TARGET_PLATFORM: ${{ matrix.target-platform-id }}
